version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      inception:
         ipv4_address: 172.18.0.12
    volumes:
      - wp_data:/var/www/
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    volumes:
      - wp_data:/var/www/
    networks:
      inception:
         ipv4_address: 172.18.0.3
    tty: true
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - wp_db:/var/lib/mysql/
    env_file:
      requirements/mariadb/.env.mariadb
    networks:
      inception:
         ipv4_address: 172.18.0.5
    restart: always

volumes:
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: home/mourdani/data/wordpress/
  wp_db:
    driver_opts:
      type: none
      o: bind
      device: /home/mourdani/data/database/

networks:
  inception:
    ipam:
      config:
        - subnet: 172.18.0.0/16
